spring:
  metrics:
    servo:
      enabled: false
movies:
  pagesize: 10
s3:
  #bucketName: cf-ab6640fa-da27-4b0b-960b-21f6e038a
  bucketName: cf-ab6640fa-da27-4b0b-960b-21f6e038a946
  endpoint: http://s3.amazonaws.com
